import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import MarqueeTop from "@/components/Header/MarqueeTop";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MarqueeTop />
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}
